site_name: Django Database Backup
site_description: This Django application provides management commands to help backup and restore your project database and media files with various storages such as Amazon S3, DropBox or local file system.
site_url: https://django-dbbackup.readthedocs.io/
repo_url: https://github.com/Archmonger/django-dbbackup
repo_name: Archmonger/django-dbbackup

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Reference:
    - Configuration: configuration.md
    - Databases: databases.md
    - Storage: storage.md
    - Commands: commands.md
    - Integration: integration.md
  - About:
    - Changelog: changelog.md
    - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Archmonger/django-dbbackup
    - icon: fontawesome/brands/python
      link: https://pypi.org/pypi/django-dbbackup/
